insert into questions (text, category) values
  ('Joined Flix before 2020', 'flix'),
  ('First-ever FlixTech Summit', 'flix'),
  ('Has worked in more than one Flix stream', 'flix'),
  ('Took a Flix bus as a customer in the last year', 'flix'),
  ('At Flix for less than 6 months', 'flix'),
  ('Knows what FPL stands for — without Googling', 'flix'),
  ('Has collaborated with someone from all 3 divisions', 'flix'),
  ('Works in a different division than you', 'flix'),
  ('Deployed on a Friday and survived', 'engineering'),
  ('Has code from 3+ years ago still running in production', 'engineering'),
  ('Has filed or been on-call for a P0 incident', 'engineering'),
  ('Uses AI tools for coding every single day', 'engineering'),
  ('Has a side project running in production right now', 'engineering'),
  ('Submitted a PR this week that was 1–5 lines', 'engineering'),
  ('Has a strong opinion about a tech choice most people don''t think about', 'engineering'),
  ('Has written documentation that someone else actually read and used', 'engineering'),
  ('Currently has more than 10 browser tabs open about work', 'engineering'),
  ('Has given a talk at an internal or external tech event in the last 12 months', 'engineering'),
  ('Speaks 3 or more languages', 'personal'),
  ('Has lived in more than 2 countries', 'personal'),
  ('Traveled more than 5 hours to get here today', 'personal'),
  ('Meeting a teammate in person for the very first time today', 'personal'),
  ('Has been to more than 5 countries in the last 2 years', 'fun'),
  ('Has cooked a meal for more than 10 people', 'fun'),
  ('Owns a pet', 'fun'),
  ('Has run a half marathon or longer', 'fun'),
  ('Can play a musical instrument', 'fun'),
  ('Has watched a sunrise this year (intentionally)', 'fun'),
  ('Prefers dark mode on everything', 'fun'),
  ('Has a morning routine that starts before 6am', 'fun'),
  ('Has read a non-fiction book in the last month', 'fun'),
  ('Has fixed something at home with duct tape or improvised tools', 'fun'),
  ('Can solve a Rubik''s cube', 'fun'),
  ('Works in a city you''ve never visited', 'custom');
